version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: booksPassword
      POSTGRES_USER: booksUser
      POSTGRES_DB: booksDB
    ports:
      - "5432:5432"

