version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: booksPassword
      POSTGRES_USER: booksUser
      POSTGRES_DB: booksDB
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://booksUser:booksPassword@postgres:5432/booksDB
